---
- name: Update APT
  become: yes
  apt:
    update_cache: yes

- name: Upgrade APT
  become: yes
  apt:
    upgrade: yes

- name: Remove unuse dependency
  become: yes
  apt:
    autoremove: yes

- name: Install node
  become: yes
  apt: 
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: Install PM2
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: persist environment variable
  become: true
  shell: |
    echo TYPEORM_CONNECTION=$TYPEORM_CONNECTION >> .env
    echo TYPEORM_ENTITIES=$TYPEORM_ENTITIES >> .env
    echo TYPEORM_HOST=$TYPEORM_HOST >> .env
    echo TYPEORM_PORT=$TYPEORM_PORT >> .env
    echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> .env
    echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> .env
    echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> .env
    echo TYPEORM_MIGRATIONS=$TYPEORM_MIGRATIONS >> .env
    echo TYPEORM_MIGRATIONS_DIR=$TYPEORM_MIGRATIONS_DIR >> .env
